#!/usr/bin/env python3
import os, re

print("DREs Quiz - Update 1")
print("=" * 40)

B = "app/src/main/java/com/example/myapplication"
R = "app/src/main/res"

# FIX 1: Question counter
p = f"{B}/QuizActivity.kt"
c = open(p).read()
c = c.replace(
    r'binding.tvProgress.text = "Question \${currentIndex + 1} of \${questions.size}"',
        'binding.tvProgress.text = "Question ${currentIndex + 1} of ${questions.size}"'
    )
        open(p,'w').write(c)
        print("Fix 1 done: Question counter")

        # FIX 2: PayPal
        p = f"{B}/DonationActivity.kt"
        c = open(p).read()
        c = re.sub(
            r'"https://www\.paypal\.com/paypalme/[^"]*"',
                '"https://www.paypal.com/donate/?business=andrejohn1500%40gmail.com&currency_code=USD"',
                    c
                    )
                    open(p,'w').write(c)
                    print("Fix 2 done: PayPal donate link")

                    # FIX 3: Leaderboard spam — best score only
                    p = f"{B}/ResultActivity.kt"
                    c = open(p).read()
                    NEW = '''    private fun submitScore(name: String, score: Int, total: Int, category: String) {
                            db.collection("leaderboard")
                                        .whereEqualTo("name", name)
                                                    .get()
                                                                .addOnSuccessListener { docs ->
                                                                                val existing = docs.firstOrNull()
                                                                                                val prevBest = existing?.getLong("score")?.toInt() ?: -1
                                                                                                                if (existing != null && prevBest >= score) {
                                                                                                                                    Toast.makeText(this, "Your best score is already $prevBest/$total", Toast.LENGTH_SHORT).show()
                                                                                                                                                        binding.btnSubmitScore.isEnabled = false
                                                                                                                                                                            binding.btnSubmitScore.alpha = 0.5f
                                                                                                                                                                                                return@addOnSuccessListener
                                                                                                                                                                                                                }
                                                                                                                                                                                                                                val data = hashMapOf<String, Any>(
                                                                                                                                                                                                                                                    "name"      to name,
                                                                                                                                                                                                                                                                        "score"     to score,
                                                                                                                                                                                                                                                                                            "total"     to total,
                                                                                                                                                                                                                                                                                                                "category"  to category,
                                                                                                                                                                                                                                                                                                                                    "timestamp" to System.currentTimeMillis()
                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                    if (existing != null) {
                                                                                                                                                                                                                                                                                                                                                                                        existing.reference.set(data)
                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                            db.collection("leaderboard").add(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Toast.makeText(this, "New best score saved!", Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            binding.btnSubmitScore.isEnabled = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            binding.btnSubmitScore.alpha = 0.5f
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .addOnFailureListener {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Toast.makeText(this, "Submission failed. Check connection.", Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }'''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c = re.sub(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        r'    private fun submitScore\(name: String.*?\n    \}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NEW, c, flags=re.DOTALL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            open(p,'w').write(c)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Fix 3 done: Leaderboard spam fixed")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # FIX 4: PLAY button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p = f"{R}/layout/activity_main.xml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c = open(p).read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c = re.sub(r'android:text="[^"]*START QUIZ"', 'android:text="PLAY"', c)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            open(p,'w').write(c)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Fix 4 done: PLAY button")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # FIX 5: Answer buttons vivid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            open(f"{R}/drawable/bg_option_default.xml",'w').write(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '<?xml version="1.0" encoding="utf-8"?>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '<ripple xmlns:android="http://schemas.android.com/apk/res/android"\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '    android:color="#FFFFD700">\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '    <item>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '        <shape android:shape="rectangle">\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '            <gradient\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '                android:angle="180"\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '                android:startColor="#1E3F7A"\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '                android:endColor="#0D2347"\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '                android:type="linear"/>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '            <corners android:radius="14dp"/>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '            <stroke\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '                android:width="2dp"\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '                android:color="#FFD700"/>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '        </shape>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '    </item>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '</ripple>\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Fix 5 done: Answer buttons gold border + ripple")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # FIX 6: Sounds via ToneGenerator
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p = f"{B}/QuizActivity.kt"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c = open(p).read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if 'ToneGenerator' not in c:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c = c.replace(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'import android.media.AudioAttributes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'import android.media.AudioAttributes\nimport android.media.AudioManager\nimport android.media.ToneGenerator'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c = c.replace(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'soundPool.play(sndCorrect, 1f, 1f, 0, 0, 1f)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'ToneGenerator(AudioManager.STREAM_MUSIC, 90).startTone(ToneGenerator.TONE_PROP_BEEP, 250)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c = c.replace(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'soundPool.play(sndWrong, 1f, 1f, 0, 0, 1f)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'ToneGenerator(AudioManager.STREAM_MUSIC, 90).startTone(ToneGenerator.TONE_PROP_NACK, 400)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    open(p,'w').write(c)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Fix 6 done: Sounds active")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("=" * 40)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("ALL FIXES DONE. Now run:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('git add -A && git commit -m "Update 1: fixes and improvements" && git push origin master')
