import json, os

OUT = "app/src/main/assets/questions"
os.makedirs(OUT, exist_ok=True)

data = {

1: [
  {"question":"To which group does a family belong?","options":["Primary group","Secondary group","Work group","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a right of every child?","options":["Right to education","Right to vote","Right to drive","None of the above"],"correctIndex":0},
  {"question":"Margaret lives with her grandparents, parents and cousins. What type of family is this?","options":["Extended family","Nuclear family","Single parent family","None of the above"],"correctIndex":0},
  {"question":"Which of the following shows cooperation among family members?","options":["Completing tasks that are assigned","Being disrespectful to each other","Refusing to take responsibility","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a role of responsible parents?","options":["Protecting children from abuse","Allowing children to do whatever they want","Ignoring children's needs","None of the above"],"correctIndex":0},
  {"question":"A neighbour helped repair Miss Sylvie's broken fence after a storm. What did the neighbour show?","options":["Neighbourliness","Favouritism","Selfishness","None of the above"],"correctIndex":0},
  {"question":"Culture is BEST defined as","options":["The way of life of a people","Only the dances of a people","Only the food of a people","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a non-renewable resource?","options":["Bauxite","Water","Plants","None of the above"],"correctIndex":0},
  {"question":"Countries put laws in place mainly to","options":["Protect the rights of citizens and reduce crime","Restrict the movement of all citizens","Control what people eat","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of cultural heritage?","options":["Traditional dress","Local currency","New buildings","None of the above"],"correctIndex":0},
  {"question":"The laws of most Caribbean countries are made in","options":["Parliament","The court","The police station","None of the above"],"correctIndex":0},
  {"question":"A patriot is a person who","options":["Loves and serves his country","Refuses to obey laws","Buys only foreign goods","None of the above"],"correctIndex":0},
  {"question":"Which workers provide a service to the community?","options":["Pharmacists, bankers and taxi drivers","Only farmers","Only factory workers","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of good citizenship?","options":["Showing respect for the property of others","Damaging the property of others","Disobeying the laws","None of the above"],"correctIndex":0},
  {"question":"Tourism is important to the Caribbean because it","options":["Creates employment opportunities for citizens","Encourages people to share all profits equally","Makes all beaches private","None of the above"],"correctIndex":0}
],

2: [
  {"question":"A family with only a mother, father and their children is called","options":["A nuclear family","An extended family","A single parent family","None of the above"],"correctIndex":0},
  {"question":"Which of the following practices contributes to good health?","options":["Practising personal hygiene","Eating as one likes","Watching television all night","None of the above"],"correctIndex":0},
  {"question":"If garbage collectors do NOT do their job, what is MOST likely to happen?","options":["An outbreak of diseases","Soil erosion","Noise pollution","None of the above"],"correctIndex":0},
  {"question":"People of African descent were brought to the Caribbean under which system?","options":["Slavery","Indentureship","Conscription","None of the above"],"correctIndex":0},
  {"question":"People of Indian descent were brought to the Caribbean under which system?","options":["Indentureship","Slavery","Volunteering","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the MOST suitable method of ensuring safe drinking water?","options":["Adding chlorine to treat it","Adding ice cubes","Reducing leaks in pipes","None of the above"],"correctIndex":0},
  {"question":"Andrea moved from her village to work in the city. This type of movement is called","options":["Internal migration","External migration","Rural migration","None of the above"],"correctIndex":0},
  {"question":"National symbols are important because they","options":["Promote pride among citizens","Identify only one ethnic group","Represent economic wealth only","None of the above"],"correctIndex":0},
  {"question":"In most Caribbean countries, general elections are due every","options":["Five years","Four years","Ten years","None of the above"],"correctIndex":0},
  {"question":"Citizens can keep their governments responsive by","options":["Participating in elections","Seeking employment only","Attending political meetings only","None of the above"],"correctIndex":0},
  {"question":"Which organisation was formed when Caribbean countries decided to work together as a trading group?","options":["CARICOM","CEDEMA","NATO","None of the above"],"correctIndex":0},
  {"question":"When Caribbean countries trade with each other this is called","options":["Interregional trade","Local trade","International trade","None of the above"],"correctIndex":0},
  {"question":"Caribbean countries trade with other countries mainly because they want to","options":["Earn foreign exchange","Protect the natural environment","Share cultural experiences only","None of the above"],"correctIndex":0},
  {"question":"Which of the following activities helps farmers preserve the environment?","options":["Replanting trees","Removing topsoil from the land","Burning sugar cane before reaping","None of the above"],"correctIndex":0},
  {"question":"Ecotourism is BEST related to the development of","options":["Nature resources","Sports only","Festivals only","None of the above"],"correctIndex":0}
],

3: [
  {"question":"Which of the following is NOT a right of a child?","options":["Marriage","Education","A name","None of the above"],"correctIndex":0},
  {"question":"A family where the father is absent and the mother raises the children alone is called","options":["A single parent family","A nuclear family","An extended family","None of the above"],"correctIndex":0},
  {"question":"Wakes and christenings are cultural celebrations associated with","options":["Death and birth","Feasts and planting","Marriage and harvest","None of the above"],"correctIndex":0},
  {"question":"In a multiracial society citizens are MOST likely to","options":["Learn to live together as a community","Lose their identity completely","Neglect their cultural activities","None of the above"],"correctIndex":0},
  {"question":"Which of the following is associated with African ancestors of Caribbean people?","options":["Telling folk stories","Planting rice only","Making pepper-pot only","None of the above"],"correctIndex":0},
  {"question":"A student joined an environmental club. Which behaviour is she MOST LIKELY to show?","options":["Making compost in her backyard","Disposing garbage in the sea","Using Styrofoam containers","None of the above"],"correctIndex":0},
  {"question":"A volcano can benefit a community because it may be used as","options":["A tourist attraction","An animal shelter","A playground","None of the above"],"correctIndex":0},
  {"question":"Which instrument is used to measure temperature?","options":["Thermometer","Barometer","Anemometer","None of the above"],"correctIndex":0},
  {"question":"Queen Elizabeth II was represented in some Caribbean countries by the","options":["Governor General","Prime Minister","Leader of the Opposition","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes a republic?","options":["Citizens vote for a President as head of state","A king or queen is head of state","A governor general is head of state","None of the above"],"correctIndex":0},
  {"question":"Mary works in a factory that makes nutmeg jam. Which industry does she work in?","options":["Secondary industry","Primary industry","Tertiary industry","None of the above"],"correctIndex":0},
  {"question":"A farmer grows bananas and sells them. Which industry is this?","options":["Primary industry","Secondary industry","Tertiary industry","None of the above"],"correctIndex":0},
  {"question":"Which TWO goods does the Caribbean commonly sell to European countries?","options":["Sugar and rum","Vehicles and engine parts","Petroleum and oil","None of the above"],"correctIndex":0},
  {"question":"A country buys fertilizer from overseas. This practice is called","options":["Importing","Exporting","Bartering","None of the above"],"correctIndex":0},
  {"question":"A country sells its bananas to another country. This is called","options":["Exporting","Importing","Bartering","None of the above"],"correctIndex":0}
],

4: [
  {"question":"Which of the following BEST describes the Caribbean Sea?","options":["A body of water surrounded by Caribbean islands and Central and South America","The largest ocean in the world","A lake found in South America","None of the above"],"correctIndex":0},
  {"question":"Which of the following countries is NOT a place from which a large number of Caribbean ancestors came?","options":["Russia","India","Africa","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the capital city of Jamaica?","options":["Kingston","Montego Bay","Spanish Town","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the capital city of Barbados?","options":["Bridgetown","Georgetown","Kingstown","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the capital city of Trinidad and Tobago?","options":["Port of Spain","Bridgetown","Georgetown","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the capital city of St. Vincent and the Grenadines?","options":["Kingstown","Castries","Roseau","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a formal group?","options":["A group with a chairperson, secretary and treasurer","A group of friends chatting","A family eating together","None of the above"],"correctIndex":0},
  {"question":"A person who sells goods from a teacher to students is providing which type of industry?","options":["Tertiary industry","Primary industry","Secondary industry","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes internal migration?","options":["Moving from one area to another within the same country","Moving from one country to another","Returning to your home country","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes external migration?","options":["Moving from one country to another country","Moving within the same country","Returning from a holiday","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a renewable resource?","options":["Water and plants","Bauxite and oil","Coal and natural gas","None of the above"],"correctIndex":0},
  {"question":"The Caribbean region has a tropical climate which means it is mainly","options":["Warm and wet throughout most of the year","Cold and snowy in winter","Dry and desert-like","None of the above"],"correctIndex":0},
  {"question":"Hurricanes in the Caribbean are caused by","options":["Warm ocean waters and atmospheric conditions creating rotating storms","Cold Arctic air moving south","Earthquakes under the ocean","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST reason why citizens should vote?","options":["To choose leaders who will represent their interests","Because it is an enjoyable activity","To get a day off work","None of the above"],"correctIndex":0},
  {"question":"Which of the following practices pollutes the environment?","options":["Dumping waste in rivers and the sea","Replanting trees after cutting","Composting food waste","None of the above"],"correctIndex":0}
],

5: [
  {"question":"The national flower of St. Vincent and the Grenadines is the","options":["Heliconia (Lobster Claw)","Hibiscus","Bougainvillea","None of the above"],"correctIndex":0},
  {"question":"St. Vincent and the Grenadines gained independence from which country?","options":["Britain","France","Spain","None of the above"],"correctIndex":0},
  {"question":"In which year did St. Vincent and the Grenadines gain independence?","options":["1979","1962","1966","None of the above"],"correctIndex":0},
  {"question":"La Soufriere is significant to St. Vincent because it is","options":["An active volcano","A famous beach","The capital city","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what CARICOM does?","options":["Promotes cooperation and development among Caribbean nations","Runs all Caribbean elections","Controls all Caribbean trade with Europe","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a national symbol of a Caribbean country?","options":["The national flag","The national currency only","The national highway","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes a constitutional monarchy?","options":["A monarch is head of state but power is limited by a constitution","One person rules with absolute power","Citizens elect a president directly","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which tourism benefits the Caribbean?","options":["It creates jobs and earns foreign exchange","It always protects the environment","It makes the cost of living lower","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a problem that tourism can cause in the Caribbean?","options":["Environmental damage and cultural commercialisation","Always increasing wages for all workers","Making all citizens wealthy","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes soil erosion?","options":["The wearing away of topsoil by wind and water","Adding nutrients to soil","Planting crops in soil","None of the above"],"correctIndex":0},
  {"question":"Reforestation means","options":["Planting new trees to replace those that were cut down","Cutting down large areas of forest","Studying trees in a forest","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a reason why Caribbean countries need to conserve their natural resources?","options":["So that resources last for future generations","Because resources are worthless","To make them more expensive","None of the above"],"correctIndex":0},
  {"question":"A group of friends who play together after school is an example of","options":["An informal group","A formal group","A government group","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the role of a community health worker?","options":["Visiting homes to provide basic health education and care","Making laws for the community","Building roads in the community","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of cultural diversity in the Caribbean?","options":["Different religions, languages and traditions existing in one community","Everyone practising the same religion","Everyone speaking the same language only","None of the above"],"correctIndex":0}
],

6: [
  {"question":"Which of the following is a cause of air pollution?","options":["Vehicle exhaust fumes and factory smoke","Planting trees","Composting waste","None of the above"],"correctIndex":0},
  {"question":"The Eastern Caribbean Dollar is used in","options":["Several Eastern Caribbean countries including SVG, St. Lucia and Grenada","Jamaica only","Trinidad and Tobago only","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what a citizen's responsibility is?","options":["Obeying laws, paying taxes and participating in community life","Only voting every five years","Only paying taxes","None of the above"],"correctIndex":0},
  {"question":"A bar graph, pie chart and line graph are all examples of","options":["Ways of presenting data and information visually","Types of maps","Types of national symbols","None of the above"],"correctIndex":0},
  {"question":"When reading a bar graph, the height of each bar tells you","options":["The value or quantity being measured","The colour of the data","The year the graph was made","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a consequence of deforestation?","options":["Soil erosion and loss of animal habitats","More rainfall in the area","Cooler temperatures","None of the above"],"correctIndex":0},
  {"question":"A worker who teaches children in school belongs to which industry?","options":["Tertiary industry","Primary industry","Secondary industry","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST example of sustainable development?","options":["Using solar energy instead of burning fossil fuels","Cutting all forests for farming","Using as many resources as possible now","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the water cycle?","options":["The continuous movement of water through evaporation, condensation and rainfall","Water flowing only in rivers","Water being stored in dams only","None of the above"],"correctIndex":0},
  {"question":"A hurricane is classified as a natural disaster because","options":["It is a severe natural event that causes great destruction to communities","It is caused by human activity","It only happens in large countries","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes a national hero?","options":["A person who represented the rights of the people of their country","A person who was very wealthy","A person who was born in the capital city","None of the above"],"correctIndex":0},
  {"question":"The Leader of the Opposition in parliament has the role of","options":["Questioning and challenging government decisions","Agreeing with everything the government does","Running the economy alone","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes heritage?","options":["Traditions and history passed down through generations","Only buildings from the past","Only old photographs","None of the above"],"correctIndex":0},
  {"question":"A farmer who grows crops is part of which industry?","options":["Primary industry","Secondary industry","Tertiary industry","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes why countries import goods?","options":["To get goods they cannot produce themselves or that are cheaper from abroad","To reduce their own production","To help other countries only","None of the above"],"correctIndex":0}
],

7: [
  {"question":"Which of the following describes Nine Mornings in St. Vincent and the Grenadines?","options":["A unique pre-Christmas cultural tradition with early morning festivities","A religious fast lasting nine days","A cricket tournament","None of the above"],"correctIndex":0},
  {"question":"The Vincentian volcano La Soufriere last had a major eruption in","options":["2021","1979","1902","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the role of the judiciary?","options":["To interpret laws and decide legal cases fairly","To make new laws for the country","To collect taxes from citizens","None of the above"],"correctIndex":0},
  {"question":"The Senate in a Caribbean parliament is described as","options":["The upper house that reviews legislation","The lower hower house where elected members sit","The court of final appeal","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean nations formed CARICOM?","options":["To give Caribbean nations greater collective strength in trade and development","To create a single Caribbean country","To control Caribbean elections","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of a primary industry in SVG?","options":["Banana and arrowroot farming","A car manufacturing plant","A call centre","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of a tertiary industry?","options":["A hotel providing tourism services","A farmer growing crops","A factory making clothes","None of the above"],"correctIndex":0},
  {"question":"What does interregional trade mean?","options":["Trade between countries within the same region","Trade between a country and a very distant continent","Trade only within one country","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an effect of overfishing on Caribbean communities?","options":["Depletion of fish stocks threatening fishing livelihoods","More fish for everyone","Lower prices for fish","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the role of the Governor General in Caribbean nations?","options":["Representing the head of state and performing constitutional duties","Running the government daily","Making laws for the country","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes bartering?","options":["Exchanging goods for other goods without using money","Selling goods for money","Importing goods from abroad","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST reason to protect mangroves in the Caribbean?","options":["They protect coastlines and serve as nurseries for marine life","They are only useful for timber","They have no environmental value","None of the above"],"correctIndex":0},
  {"question":"Crop rotation is beneficial to farmers because it","options":["Maintains soil fertility by growing different crops in the same field each season","Destroys pests permanently","Removes the need for irrigation","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what a constitution does?","options":["Sets out the basic laws and rights of a country","Lists all citizens of a country","Describes the country's geography","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way citizens can hold their government accountable?","options":["Voting, peaceful protest and contacting their representatives","Only paying taxes","Only attending government functions","None of the above"],"correctIndex":0}
],

8: [
  {"question":"Africans were brought to the Caribbean mainly to","options":["Work as enslaved labourers on sugar and other plantations","Settle as free farmers","Trade with indigenous peoples","None of the above"],"correctIndex":0},
  {"question":"The abolition of slavery in British Caribbean colonies happened in","options":["1838","1808","1900","None of the above"],"correctIndex":0},
  {"question":"Workers from India came to the Caribbean after emancipation under a system called","options":["Indentureship","Slavery","Volunteering","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the impact of the African heritage on Caribbean culture?","options":["Contributed music, dance, storytelling, food and spiritual practices that shape Caribbean identity","Had no lasting cultural impact","Only influenced religion","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a traditional food associated with Indian heritage in the Caribbean?","options":["Roti and curry","Fish and chips","Jerk chicken","None of the above"],"correctIndex":0},
  {"question":"La Soufriere in SVG is an example of which type of landform?","options":["A volcano","A coral reef","A delta","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what a coral reef provides?","options":["A habitat for marine life and protection for coastlines","Only a tourist attraction","Only a source of sand","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a NEGATIVE effect of climate change on the Caribbean?","options":["More intense hurricanes and rising sea levels","Better farming conditions everywhere","Cooler ocean temperatures","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why the Caribbean is vulnerable to natural disasters?","options":["Its location in the hurricane belt and presence of volcanic and seismic activity","It has no early warning systems","It has no mountains or coastlines","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes a subsistence farmer?","options":["A farmer who grows food mainly to feed their own family","A farmer who exports all their produce","A farmer who works in a factory","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST description of foreign exchange?","options":["Money earned from selling goods and services to other countries","Money borrowed from other countries","Gifts received from abroad","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of a community organisation in the Caribbean?","options":["A parent-teacher association","A national army","A parliament","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the role of media in a democracy?","options":["Informing the public and holding government accountable","Making laws for the country","Running elections","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a consequence of water pollution in Caribbean communities?","options":["Spread of waterborne diseases affecting health","Improved fishing catches","Better drinking water","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST way to conserve water at home?","options":["Fixing leaking pipes and using water wisely","Leaving taps running","Using more water in the dry season","None of the above"],"correctIndex":0}
],

9: [
  {"question":"Which of the following BEST describes the impact of the Haitian Revolution on Caribbean history?","options":["It was the first successful revolt by enslaved people leading to an independent Black republic in 1804","It was a minor local event with no lasting impact","It was led by European settlers","None of the above"],"correctIndex":0},
  {"question":"The OECS stands for","options":["Organisation of Eastern Caribbean States","Organisation of European Caribbean States","Organisation for Eastern Commerce","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a function of the OECS?","options":["Promoting economic cooperation among smaller Eastern Caribbean states","Running elections in Eastern Caribbean countries","Controlling the Caribbean Sea","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what foreign investment means for a Caribbean country?","options":["Money from another country used to build businesses and create jobs locally","Money sent by Caribbean nationals living abroad","Loans from Caribbean banks","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a cause of soil erosion?","options":["Deforestation and overfarming on slopes","Planting trees on hillsides","Building terraces on farms","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the difference between weather and climate?","options":["Weather is day to day conditions; climate is the average pattern over many years","Weather and climate are exactly the same","Climate changes daily while weather stays the same","None of the above"],"correctIndex":0},
  {"question":"Reading a pie chart, the largest slice represents","options":["The category with the greatest value or percentage","The least popular category","The oldest data","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why the Caribbean has a diverse cultural heritage?","options":["Because people from Africa, India, Europe and indigenous peoples all contributed to Caribbean culture","Because only one group of people settled in the Caribbean","Because the Caribbean was always isolated","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a Caribbean industry that depends directly on the natural environment?","options":["Tourism and fishing","Car manufacturing","Steel production","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of sustainable fishing?","options":["Catching only what is needed and allowing fish stocks to recover","Using large nets to catch all available fish","Fishing in protected marine areas","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way the government of SVG promotes national identity?","options":["Through national symbols, holidays and cultural festivals","By banning foreign music","By controlling all media","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the importance of Emancipation Day celebrations in the Caribbean?","options":["It commemorates the end of slavery and honours the ancestors of Caribbean people","It celebrates the arrival of Europeans","It marks the start of the hurricane season","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way that citizens can participate in their community?","options":["Volunteering, attending community meetings and keeping the environment clean","Only by voting in elections","Only by paying taxes","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what biodiversity means?","options":["The variety of plant and animal life in a habitat","Only the number of trees in a forest","Only the number of fish in the sea","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the importance of protecting watersheds in the Caribbean?","options":["They supply clean water for communities and support agriculture","They are only important for swimming","They have no practical value","None of the above"],"correctIndex":0}
],

10: [
  {"question":"Columbus's voyage in 1492 was significant because it","options":["Began European contact with the Caribbean leading to colonisation","Ended slavery in the Caribbean","Founded CARICOM","None of the above"],"correctIndex":0},
  {"question":"The plantation system in the Caribbean was mainly used to","options":["Produce sugar and other crops using enslaved African labour for export to Europe","Grow food for local communities","Train skilled craftsmen","None of the above"],"correctIndex":0},
  {"question":"The Caribbean Court of Justice serves as","options":["The final court of appeal for CARICOM member states","The court that makes new Caribbean laws","The organisation that runs Caribbean elections","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the role of a trade union?","options":["Protecting workers rights and negotiating better wages and conditions","Selling goods in a market","Making laws for the government","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what the national budget is?","options":["The government's plan for collecting and spending money on public services","A list of national laws","A plan for running elections","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how the Indian heritage has influenced Caribbean culture?","options":["Roti, curry, Hindi music and Divali celebrations","Only the English language","Only Christian churches","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a POSITIVE impact of migration on a Caribbean community?","options":["Remittances sent home support families and boost the local economy","Everyone always leaves and never returns","The country loses all its skilled workers permanently","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why protecting coral reefs is important for Caribbean fishing?","options":["Coral reefs are nurseries for fish; healthy reefs support fish populations that fishing communities depend on","Coral reefs produce fish directly","Coral reefs have no connection to fishing","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a method used to show information on a line graph?","options":["Points connected by lines showing change over time","Slices of a circle showing proportions","Bars of different heights showing quantities","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the impact of natural disasters on Caribbean development?","options":["They destroy infrastructure and set back development requiring years of rebuilding","They have no lasting economic impact","They always bring international aid that helps countries develop faster","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a reason why Caribbean countries need to develop renewable energy?","options":["To reduce dependence on expensive imported fossil fuels and protect the environment","Because renewable energy is always free","Because fossil fuels are found in every Caribbean country","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes what sovereignty means for a Caribbean nation?","options":["Having full independent authority over its own territory and decisions","Being controlled by a larger country","Having the largest military","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which agriculture benefits SVG?","options":["Provides food, employment and exports earning foreign exchange","Only provides food for farmers","Has no economic benefit","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the importance of the freedom to vote?","options":["It allows citizens to choose their government and hold leaders accountable","It is only important for educated people","It has no real impact on how the country is run","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way climate change threatens food security in the Caribbean?","options":["Irregular rainfall, stronger storms and saltwater intrusion damage crops and fish stocks","Climate change only affects cold countries","Climate change improves farming conditions in the Caribbean","None of the above"],"correctIndex":0}
]

}

for level, questions in data.items():
    filepath = os.path.join(OUT, f"cpea_social_studies_l{level}.json")
    with open(filepath, 'w') as f:
        json.dump(questions, f, indent=2)
    print(f"Written level {level}")

print("Levels 1-10 done!")
import json, os

OUT = "app/src/main/assets/questions"
os.makedirs(OUT, exist_ok=True)

data = {

11: [
  {"question":"Which of the following BEST describes the impact of the plantation system on Caribbean social structure?","options":["It created a racially divided society with Europeans at the top and enslaved Africans at the bottom","It created equal opportunities for all groups","It had no lasting effect on Caribbean society","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why the Caribbean has such a diverse population today?","options":["Because Africans, Indians, Europeans, Chinese and indigenous peoples all came to or were brought to the region at different times","Because only one group of people settled in the region","Because the Caribbean has always been isolated from the rest of the world","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which the government of SVG provides services to citizens?","options":["Building schools, hospitals and roads and providing police protection","Only collecting taxes","Only running elections","None of the above"],"correctIndex":0},
  {"question":"A factory worker who makes furniture from timber is part of which industry?","options":["Secondary industry","Primary industry","Tertiary industry","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what remittances are?","options":["Money sent home by Caribbean nationals living and working abroad","Money borrowed from international banks","Taxes paid to the government","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way that deforestation affects the Caribbean water cycle?","options":["Fewer trees means less transpiration which can reduce rainfall in an area","More trees would reduce rainfall","Deforestation has no effect on the water cycle","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how citizens can protect their environment?","options":["Reducing use of plastics, recycling and not polluting rivers and beaches","Using more fossil fuels","Cutting down forests for farming","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the difference between a need and a want?","options":["A need is essential for survival such as food and water; a want is desired but not essential such as a toy","Wants are more important than needs","Needs and wants are the same thing","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a festival that reflects the African heritage of Caribbean people?","options":["Carnival with its music costumes and dancing rooted in emancipation celebrations","Divali which reflects Indian heritage","Christmas which is of European origin","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what a community needs to thrive?","options":["Good leadership, services, cooperation among residents and a safe environment","Only money","Only a strong police force","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the impact of coral reef destruction on Caribbean tourism?","options":["Damaged reefs reduce the appeal of the Caribbean for diving and snorkelling tourists reducing income","Reef destruction attracts more tourists","It has no effect on tourism","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST reason why education is important in the Caribbean?","options":["It builds skills that help people improve their lives and contribute to national development","It is only useful for getting a job","It is only important for wealthy families","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the impact of a hurricane on a Caribbean farming community?","options":["Crops are destroyed, livelihoods are lost and food security is threatened","Farming always improves after a hurricane","Hurricanes only affect coastal areas not farms","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how the Indian community has contributed to Caribbean agriculture?","options":["Bringing rice and sugarcane farming techniques and establishing strong agricultural communities","Having no impact on agriculture","Only contributing to fishing","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the role of the police in a Caribbean community?","options":["Maintaining law and order, preventing crime and protecting citizens","Making new laws","Running the courts","None of the above"],"correctIndex":0}
],

12: [
  {"question":"Which of the following BEST explains why universal adult suffrage was important in Caribbean history?","options":["It gave all adults the right to vote regardless of race or class moving the Caribbean toward true democracy","It only benefited wealthy citizens","It had no impact on Caribbean politics","None of the above"],"correctIndex":0},
  {"question":"A line graph showing tourist arrivals over ten years is MOST useful for","options":["Showing trends and changes in tourism over time","Showing the proportion of tourists from different countries","Comparing amounts at one point in time","None of the above"],"correctIndex":0},
  {"question":"A pie chart showing sources of government revenue is MOST useful for","options":["Showing what proportion of revenue comes from each source such as taxes and tourism","Showing how revenue has changed over time","Comparing revenue of different countries","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a NEGATIVE impact of large-scale tourism on a Caribbean island?","options":["Pressure on water supplies, beaches and reefs and high economic leakage when profits go to foreign companies","More jobs for all citizens","Lower cost of living for residents","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what economic leakage means in Caribbean tourism?","options":["When a large portion of tourism earnings leaves the country because hotels and services are foreign-owned","When tourists spend too little money","When tourist numbers decline","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of a Caribbean country using its natural resources sustainably?","options":["Managing fisheries carefully to prevent overfishing and allow stocks to recover","Catching all available fish as quickly as possible","Cutting all remaining forests for farmland","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the importance of the Caribbean Sea to the region?","options":["It supports fishing, tourism, trade routes and the livelihoods of millions of Caribbean people","It is only important for swimming","It is only used by large cargo ships","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which families can conserve energy at home?","options":["Turning off lights and appliances when not in use and using energy-efficient bulbs","Leaving all appliances on all day","Using more air conditioning","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the difference between a democracy and a dictatorship?","options":["In a democracy citizens elect their leaders; in a dictatorship one person rules with unchecked power","They are the same form of government","A dictatorship is more fair than a democracy","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean nations need to prepare for natural disasters?","options":["Because the Caribbean is vulnerable to hurricanes, volcanic eruptions, earthquakes and flooding which can devastate communities","Because natural disasters never cause serious damage in the Caribbean","Because the Caribbean only experiences mild weather events","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how the government of SVG promotes cultural heritage?","options":["Supporting Nine Mornings celebrations, Vincy Mas carnival and cultural education in schools","By banning all foreign cultural influences","Only through sports events","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST description of what the Caribbean Single Market means for workers?","options":["Skilled Caribbean nationals can move and work freely in other CARICOM member states","Only professionals can move between countries","Only businesspeople benefit from the Single Market","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which climate change affects Caribbean water resources?","options":["More droughts in some areas and more flooding in others making water supply less reliable","Climate change always increases fresh water availability","The Caribbean has no water shortage concerns","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what the informal economy is?","options":["Economic activities like street vending that are not registered or taxed by the government","The government-run sector of the economy","Large businesses that operate informally","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which young people can contribute to their Caribbean community?","options":["Volunteering, participating in civic activities, respecting the environment and staying in school","Only by earning money","Only after becoming adults","None of the above"],"correctIndex":0}
],

13: [
  {"question":"Which of the following BEST explains why the Caribbean needs to reduce dependence on imported food?","options":["To improve food security, save foreign exchange and protect communities from global price shocks","Because imported food is always unhealthy","Because the Caribbean produces no food at all","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the impact of the brain drain on Caribbean countries?","options":["Educated and skilled people leave reducing the human capital available for national development","It has no impact on the countries they leave","It only affects small islands","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which the Caribbean diaspora contributes to development?","options":["Sending remittances, investing in businesses and sharing skills and knowledge with their home countries","Only by returning home permanently","Only by sending money occasionally","None of the above"],"correctIndex":0},
  {"question":"A bar chart shows that banana exports fell from 2010 to 2020. What is the MOST LIKELY cause?","options":["Competition from cheaper bananas from other regions and impact of storms on crops","Vincentians stopped liking bananas","The government banned banana farming","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the blue economy concept for the Caribbean?","options":["Sustainable use of ocean resources including fisheries, shipping and marine tourism for economic growth","An economy that only uses the colour blue","Only about fishing","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how SVG's geography affects its economy?","options":["Mountainous terrain limits large-scale farming but supports eco-tourism and niche agriculture like arrowroot","The flat terrain makes large-scale farming easy everywhere","SVG has no natural features of economic value","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what food security means?","options":["When all people have reliable access to enough nutritious food to lead healthy lives","When a country grows all its own food","When food is locked away safely","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a challenge that small island developing states like SVG face?","options":["Limited resources, vulnerability to natural disasters and climate change and dependence on a few industries","No challenges compared to larger countries","Only economic challenges","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how cooperation among Caribbean nations helps during a disaster?","options":["Countries share resources, personnel and expertise because no small island can manage a major disaster alone","Each country must always manage disasters alone","Cooperation is not useful during disasters","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the impact of plastic pollution on Caribbean marine life?","options":["Marine animals ingest or get entangled in plastic causing injury and death and damaging entire ecosystems","Plastic pollution only affects beaches not marine life","Marine life is unaffected by plastic pollution","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the role of civic education in Caribbean schools?","options":["Teaching students their rights and responsibilities and how to participate meaningfully in their communities and democracy","Only teaching history","Only preparing students for elections when they are adults","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how technology has improved life in Caribbean communities?","options":["Access to internet for education, e-government services, mobile banking and better communication","Technology has only brought problems","Only wealthy communities benefit from technology","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean countries promote cultural festivals internationally?","options":["To attract tourists, earn foreign exchange and share Caribbean culture and identity with the world","Only to entertain locals","Only because governments require it","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which poor sanitation affects community health?","options":["It spreads waterborne diseases like cholera especially affecting children and vulnerable community members","It has no health impacts","It only affects adults","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what sustainable agriculture means?","options":["Farming in ways that maintain soil health, protect the environment and can continue productively for future generations","Using as many chemicals as possible to increase production","Cutting all forests to create more farmland","None of the above"],"correctIndex":0}
],

14: [
  {"question":"Which of the following BEST explains why Caribbean nations must balance tourism development with environmental protection?","options":["Because the very natural beauty and culture that attract tourists will be destroyed if not properly managed threatening the tourism industry itself","Because tourists prefer damaged environments","Because environmental protection has no connection to tourism","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the significance of Vincy Mas to Vincentian culture?","options":["It is SVG's major carnival celebration reflecting creative expression, African heritage and national identity","It is only an event for tourists","It has no cultural significance","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the difference between a federal and a unitary system of government?","options":["Federal systems divide power between central and regional governments; unitary systems keep power mainly in the central government","They are the same system","Federal systems only exist in large countries","None of the above"],"correctIndex":0},
  {"question":"A student reads a graph showing SVG's population from 1980 to 2020. The line is mostly flat. This MOST LIKELY means","options":["SVG's population has stayed relatively stable with emigration balancing births over this period","The population doubled every decade","There was no population data collected","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean governments invest in education and health?","options":["Healthy educated citizens are more productive and contribute more to national development and economic growth","Education and health are only government obligations not investments","Only wealthy families benefit from government services","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which the arrowroot industry is significant to SVG?","options":["SVG is one of the world's main producers of arrowroot starch which is exported and provides livelihoods","Arrowroot is only grown for local consumption","SVG grows very little arrowroot","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what nationalisation means?","options":["When the government takes ownership and control of a private industry","When a business is sold to foreign investors","When a business closes down","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which the Caribbean celebrates its cultural diversity?","options":["Through multicultural festivals, food fairs, religious celebrations and inclusive national events","By having only one culture represented","By discouraging minority cultures","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what an embargo means in international trade?","options":["An official ban on trade with a particular country","A special trade agreement between two countries","A tax on imported goods","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean countries must address climate change together?","options":["Because climate change affects all Caribbean nations and collective action through CARICOM and international bodies is more powerful than individual efforts","Because climate change only affects one or two islands","Because only large countries need to address climate change","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which the Garifuna heritage contributes to SVG's cultural identity?","options":["Through their history, language, music, dance and their presence on the island of Garifuna Settlement that enriches Vincentian heritage","The Garifuna have no connection to SVG","The Garifuna only arrived recently","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes why Caribbean countries need to diversify their economies?","options":["Relying on one or two industries like tourism or bananas makes countries very vulnerable when those industries face problems","Because diversification has no economic benefit","Because all Caribbean countries already have diverse economies","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes the role of the Electoral Commission in a Caribbean country?","options":["Organising and overseeing free and fair elections to ensure democratic processes are upheld","Making new laws","Running the court system","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which Caribbean countries can reduce the impact of natural disasters?","options":["Investing in early warning systems, enforcing building codes and educating communities about preparedness","Ignoring the risk of natural disasters","Only building sea walls","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what sustainable development means for a small Caribbean island?","options":["Meeting the needs of today's citizens without destroying the natural and cultural resources that future generations will need","Using all resources as quickly as possible","Developing only for tourists","None of the above"],"correctIndex":0}
],

15: [
  {"question":"Which of the following BEST describes the legacy of colonialism on Caribbean economies?","options":["Caribbean economies were oriented toward producing raw materials for Europe creating dependency patterns that still influence development today","Colonialism had only positive effects on Caribbean economies","Caribbean economies were fully self-sufficient during colonial times","None of the above"],"correctIndex":0},
  {"question":"A graph shows that SVG's tourism arrivals increased every year from 2015 to 2019 then dropped sharply in 2020. What is the MOST LIKELY explanation?","options":["The COVID-19 pandemic caused a sharp decline in international travel in 2020","Tourism has never been important to SVG","The SVG government banned tourism in 2020","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the importance of the Caribbean to global biodiversity?","options":["The Caribbean is considered a biodiversity hotspot with many plant and animal species found nowhere else on Earth","The Caribbean has very little plant and animal diversity","Only the rainforests of SVG have unique species","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what a green economy means for the Caribbean?","options":["An economy that grows by investing in renewable energy, eco-tourism and sustainable agriculture rather than polluting industries","An economy where everything is painted green","An economy that only grows crops","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean people celebrate Emancipation Day every August 1st?","options":["To honour the memory of enslaved ancestors, celebrate freedom and reflect on the journey from slavery to independence","Because it is a requirement of CARICOM","Only to get a public holiday","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes why local food production is important for SVG?","options":["It reduces dependence on expensive food imports, provides employment and supports food security when global supply chains are disrupted","Because SVG does not import any food","Because local food is always cheaper than imports","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST example of how SVG uses its natural environment for economic benefit?","options":["Eco-tourism, fishing, agriculture and the Botanical Gardens attract visitors and support livelihoods","SVG has no natural attractions of economic value","Only the beaches are economically useful","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the significance of the Caribbean to world history?","options":["The Caribbean was a crossroads of European African and indigenous civilisations and the plantation system shaped the modern global economy","The Caribbean had no significance to world history","Only Columbus's voyage was historically significant","None of the above"],"correctIndex":0},
  {"question":"Which of the following describes what happens when a country has a trade deficit?","options":["The country imports more than it exports meaning more money leaves the country than comes in","The country exports more than it imports","Trade is perfectly balanced","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains how the Caribbean region can achieve energy independence?","options":["By investing in renewable energy sources like solar, wind and geothermal power that the Caribbean has in abundance","By importing more fossil fuels","By reducing energy use to zero","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains how good governance contributes to development in the Caribbean?","options":["Transparent honest and accountable government attracts investment maintains stability and ensures public resources reach citizens","Good governance has no impact on development","Only the economy matters for development not governance","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a way in which Caribbean youth can address climate change?","options":["Advocating for climate action, adopting sustainable practices, participating in community clean-ups and raising awareness","Young people have no role in addressing climate change","Only governments can address climate change","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the relationship between healthy ecosystems and Caribbean livelihoods?","options":["Healthy forests, reefs and seas directly support farming, fishing and tourism which millions of Caribbean people depend on for income","Ecosystems have no connection to people's livelihoods","Only farmers depend on healthy ecosystems","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what regional integration has achieved for the Caribbean?","options":["Free movement of people, goods and services, collective bargaining in international negotiations and shared disaster response","Regional integration has had no benefits","Integration only benefits large Caribbean countries","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why it is important for Caribbean citizens to be informed about government decisions?","options":["Informed citizens can participate meaningfully in democracy, hold leaders accountable and advocate for their communities","Only politicians need to understand government decisions","Citizens have no role in influencing government","None of the above"],"correctIndex":0}
],

16: [
  {"question":"Using a graph that shows average rainfall in SVG by month, during which months would farmers MOST LIKELY schedule planting?","options":["In the months with reliable rainfall that support crop growth","In the driest months of the year","Rainfall does not affect planting schedules","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the economic importance of the fishing industry to coastal communities in SVG?","options":["It provides food, employment and income for thousands of families in coastal villages","Fishing only benefits large commercial companies","Fishing is no longer economically significant","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains how Caribbean nations are particularly vulnerable to global economic shocks?","options":["Small open economies dependent on tourism and a few exports are severely affected when world economic conditions change","Caribbean economies are well protected from global changes","Only large Caribbean countries are affected by global economics","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what indigenous knowledge means for Caribbean environmental management?","options":["Traditional knowledge about plants, weather and ecosystems held by Amerindian and other communities offers valuable insights alongside modern science","Indigenous knowledge is outdated and has no value","Only scientific knowledge is useful for managing the environment","None of the above"],"correctIndex":0},
  {"question":"Which of the following is an example of how SVG's volcanic soil benefits agriculture?","options":["Volcanic soil is extremely fertile supporting strong growth of crops like bananas, arrowroot and vegetables","Volcanic soil is too toxic for farming","SVG's soil has no special agricultural qualities","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes why Caribbean nations need strong institutions?","options":["Strong courts, elections commissions and public service ensure laws are respected, elections are fair and services reach citizens","Institutions are only important in large countries","Caribbean countries do not need formal institutions","None of the above"],"correctIndex":0},
  {"question":"A Caribbean country's GDP increases but poverty also increases. What does this MOST LIKELY suggest?","options":["Economic growth is not being shared equally and the benefits are concentrated among a small wealthy group","GDP growth always reduces poverty","The data must be incorrect","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the connection between gender equality and national development?","options":["When all genders have equal opportunities a country benefits from the full talents and productivity of its entire population","Gender equality has no connection to development","Only economic factors drive development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how the Garifuna people came to live in SVG?","options":["The Garifuna are descendants of indigenous Caribs and enslaved Africans who mixed on St. Vincent and fiercely resisted British colonisation","The Garifuna arrived from Europe","The Garifuna came from Asia","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST reason why Caribbean countries should protect their mangrove forests?","options":["Mangroves protect coastlines from storm surge, store carbon, filter water and support marine nurseries all vital for Caribbean survival","Mangroves are only useful for timber","Mangroves have no environmental value","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what civic literacy means for Caribbean students?","options":["Understanding how government works, knowing your rights and responsibilities and being able to participate effectively in community and national life","Only reading about Caribbean history","Only knowing the names of government ministers","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why preserving Caribbean languages and dialects matters?","options":["They carry the history, culture and identity of communities and their loss would mean losing an irreplaceable part of Caribbean heritage","Dialects are only slang with no cultural value","Only official languages matter","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST example of how SVG demonstrates national pride?","options":["Through national symbols, the national anthem, Independence Day celebrations and support for Vincentian athletes and artists internationally","Only by winning sports competitions","Only through government speeches","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the impact of HIV/AIDS on Caribbean communities?","options":["It affects workforce productivity, healthcare costs and family structures requiring community awareness and support","HIV/AIDS is not a concern in the Caribbean","It only affects elderly people","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what the rule of law means for Caribbean citizens?","options":["That everyone including government must follow the same laws protecting rights and preventing abuse of power","That only citizens must follow the law not the government","That laws only apply in certain situations","None of the above"],"correctIndex":0}
],

17: [
  {"question":"A student compares a graph of hurricane frequency in the Caribbean from 1980 to 2020. The trend shows more frequent strong hurricanes. What does this MOST LIKELY indicate?","options":["That climate change is intensifying hurricane activity in the Caribbean region","That Caribbean countries are less prepared than before","That the data was collected incorrectly","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean nations advocate strongly for global climate action?","options":["As small island developing states the Caribbean faces existential threats from sea level rise and intensified storms that they did little to cause","Caribbean countries are major contributors to climate change","Climate change only affects Caribbean beaches not people","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how Caribbean cultural music has influenced the world?","options":["Reggae, calypso, soca and dancehall have spread globally influencing music culture and social commentary far beyond the Caribbean","Caribbean music has had no global influence","Only classical Caribbean music is known internationally","None of the above"],"correctIndex":0},
  {"question":"Which of the following is the BEST explanation of why land reform is important in the Caribbean?","options":["Fairer distribution of land addresses historical inequalities from the plantation era and gives small farmers resources to build livelihoods","Land reform has no connection to Caribbean history","All Caribbean land is already fairly distributed","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what ecotourism involves?","options":["Responsible travel to natural areas that conserves the environment and improves the wellbeing of local communities","Tourism only for wealthy visitors","Building large hotels in natural areas","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains how Caribbean people have shown resilience throughout their history?","options":["By surviving slavery, colonialism, natural disasters and economic hardship while maintaining culture, rebuilding communities and achieving independence","Caribbean history shows only weakness and hardship","Caribbean people have not shown significant resilience","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the significance of the University of the West Indies to the Caribbean?","options":["It provides higher education across the region building the skilled professionals that Caribbean nations need for development","It is only relevant for students from large Caribbean countries","Higher education has no importance to Caribbean development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how women's empowerment contributes to Caribbean development?","options":["When women are educated, employed and in leadership positions communities benefit from their full contribution to economic and social life","Women's empowerment has no development impact","Only economic empowerment matters","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the importance of family stability to a Caribbean child's development?","options":["Stable loving families provide the security, guidance and support that allow children to thrive emotionally, academically and socially","Family structure has no impact on a child's development","Only wealthy families can provide for children's development","None of the above"],"correctIndex":0},
  {"question":"Which of the following is a POSITIVE example of how technology is changing Caribbean agriculture?","options":["Farmers using mobile apps for weather information, digital marketplaces to sell produce and modern irrigation systems to improve yields","Technology has only harmed Caribbean agriculture","Only large farms can benefit from technology","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean nations work together through CARICOM on health issues?","options":["Disease does not respect borders and collective action on public health produces better outcomes than each small island acting alone","Health is not a regional concern","CARICOM does not address health issues","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the relationship between the Caribbean environment and the tourist economy?","options":["The Caribbean's natural beauty including beaches reefs and rainforests IS the product that tourism sells requiring careful protection","The environment has no connection to Caribbean tourism","Only hotels matter for tourism not the natural environment","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Vincentian students should understand Caribbean history?","options":["Because Caribbean history shaped the society, culture and economy they live in today and understanding it helps them build a better future","History has no relevance to modern life","Only Vincentian history matters not Caribbean history broadly","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what consumer rights mean for Caribbean citizens?","options":["The right to safe products, honest information, fair prices and recourse if products or services fail to meet standards","Consumers have no rights","Consumer rights only apply to expensive purchases","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the impact of political stability on Caribbean development?","options":["Stable democratic governance attracts investment, enables long-term planning and builds the trust needed for sustained economic and social progress","Political stability has no impact on development","Only economic policies matter not political stability","None of the above"],"correctIndex":0}
],

18: [
  {"question":"Using a graph showing SVG's export earnings by product, a student notices arrowroot earnings fell sharply while tourism rose. What does this MOST LIKELY reflect?","options":["A structural shift in the economy from agriculture toward services and tourism over recent decades","Arrowroot became more popular","Tourism earnings fell","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the concept of opportunity cost for a Caribbean government?","options":["When the government spends money on one thing such as a new hospital it cannot spend that same money on something else such as roads requiring careful prioritisation","Governments can always spend on everything simultaneously","Opportunity cost only applies to businesses","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how education contributes to reducing poverty in the Caribbean?","options":["Education provides skills and qualifications that increase earning potential helping individuals and families break the cycle of poverty over generations","Education has no impact on poverty","Only tertiary education reduces poverty","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean farmers are increasingly practising organic agriculture?","options":["Organic farming protects soil health, reduces chemical pollution, can command higher prices internationally and meets growing consumer demand","Organic farming produces lower yields than chemical farming with no compensating benefits","Organic farming is only possible on large farms","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what community resilience means in the context of Caribbean natural disasters?","options":["The ability of a community to prepare for, withstand, recover from and adapt after a natural disaster drawing on local knowledge, cooperation and resources","Communities cannot build resilience to natural disasters","Only government can build disaster resilience","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how the Internet has both helped and challenged Caribbean education?","options":["It has expanded access to learning resources globally but also brought challenges like misinformation, cyberbullying and unequal access creating a digital divide","The internet has only improved education","The internet has only harmed education","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean nations promote regional identity alongside national identity?","options":["Because Caribbean peoples share history, culture and challenges and a strong regional identity gives small states more power and purpose collectively","Regional identity replaces national identity","National identity is more important than regional identity","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how sustainable fishing practices protect Caribbean livelihoods?","options":["By preventing overfishing sustainable practices ensure fish populations recover so fishing communities can continue to earn their living for generations","Sustainable fishing reduces catch so much it destroys fishing communities","All fishing is automatically sustainable","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the connection between health and national productivity?","options":["Healthy citizens are more productive in school and work contributing more to economic output and national development","Health has no connection to productivity","Only mental health matters for productivity","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how deforestation in SVG threatens water security?","options":["Forests act as water catchments; losing them reduces water storage, increases runoff and can cause both flooding and dry-season water shortages","Deforestation has no effect on water availability in SVG","Only urban areas face water security challenges","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why civic participation beyond voting strengthens Caribbean democracy?","options":["Community involvement, peaceful advocacy and engaging with representatives creates an active citizenry that holds government continuously accountable not just at election time","Voting every five years is sufficient civic participation","Citizens have no role between elections","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what integrated pest management means for Caribbean farmers?","options":["Using a combination of biological, cultural and minimal chemical methods to control pests in ways that protect the environment and human health","Using as many pesticides as possible","Allowing pests to destroy crops naturally","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the importance of the Caribbean to the global tourism industry?","options":["The Caribbean is one of the world's top tourist destinations attracting millions of visitors annually with its natural beauty culture and warm climate","The Caribbean is only a minor tourist destination","Caribbean tourism only serves regional visitors","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what human development means beyond just economic growth?","options":["Improving people's health, education, rights and overall quality of life so they can live long fulfilling and creative lives","Human development only means increasing GDP","Only economic factors measure development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the role of international organisations like the United Nations in supporting Caribbean development?","options":["Providing technical assistance, funding, advocacy for small island states and frameworks for addressing global challenges like climate change and poverty","The UN controls Caribbean governments","International organisations have no role in Caribbean development","None of the above"],"correctIndex":0}
],

19: [
  {"question":"A student examines a chart showing that SVG receives more rainfall on its windward east coast than its leeward west coast. What geographic factor BEST explains this?","options":["The mountainous interior forces moisture-laden trade winds upward causing more rainfall on the windward side","The west coast is further from the sea","The east coast is lower in elevation","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains how the plantation legacy continues to affect land distribution in SVG today?","options":["Land ownership remains unequal partly reflecting colonial land grants meaning small farmers often lack access to sufficient productive land","Land in SVG is now distributed completely equally","The plantation system had no lasting effect on land ownership","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what a sustainable tourism policy for SVG should include?","options":["Limits on development in sensitive areas, community benefit requirements for tourism businesses, training for local workers and protection of natural and cultural heritage","Allowing unlimited hotel construction everywhere","Keeping all tourists away from natural areas","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean nations must balance economic openness with protecting local industries?","options":["Open markets bring competition that can drive down prices and improve quality but can also destroy local industries that cannot compete without some protection","Caribbean countries should only trade within the region","Protecting all industries always leads to better outcomes","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the connection between healthy families and a well-functioning Caribbean society?","options":["Strong families that nurture children produce capable responsible citizens who contribute positively to their communities and the broader national development","Family structure has no connection to social outcomes","Only economic factors produce a well-functioning society","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the significance of Carnival to Caribbean regional identity?","options":["Carnival across the Caribbean from Trinidad to SVG shares roots in the emancipation of enslaved people and represents a common expression of Caribbean creativity and freedom","Carnival is only a tourist event with no cultural meaning","Caribbean carnivals have no connection to each other","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the importance of press freedom to Caribbean democracy?","options":["A free press investigates corruption, informs citizens of government actions and provides a platform for public debate strengthening democratic accountability","Press freedom is only important for journalists","Government should control what the press reports","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how SVG can use its cultural diversity as an economic asset?","options":["By promoting diverse food, music, art and festivals SVG can attract tourists interested in authentic Caribbean culture creating employment and income","Cultural diversity has no economic value","Only natural attractions can drive SVG's economy","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why reparations is a significant debate in the Caribbean today?","options":["Caribbean nations and scholars argue that the wealth generated by enslaved Caribbean labour enriched Europe and that descendants deserve acknowledgement and compensation for this historical injustice","Reparations is not a serious issue","The Caribbean has no basis for discussing reparations","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what an informed and active citizen contributes to Caribbean development?","options":["By voting wisely, holding leaders accountable, participating in community improvement and respecting the environment active citizens drive development from the ground up","Citizens have no meaningful impact on development","Only government drives development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the connection between protecting Caribbean biodiversity and economic sustainability?","options":["Biodiversity underpins fisheries, agriculture, medicine and eco-tourism meaning its loss would directly harm the livelihoods and food security of Caribbean communities","Biodiversity has no economic value","Only marine biodiversity matters for economics","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why Caribbean countries prioritise disaster preparedness education in schools?","options":["Children who learn what to do during hurricanes, floods and volcanic eruptions are safer and grow into adults who build more resilient communities","Disaster preparedness is only for adults","Schools have no role in disaster preparedness","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what good governance means in the Caribbean context?","options":["Government that is transparent, accountable, responsive to citizens' needs, upholds the rule of law and manages public resources honestly","Good governance only means low taxes","Good governance only means strong economic growth","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains how SVG can reduce its vulnerability to natural disasters over the long term?","options":["Through better land use planning, stronger building standards, protecting natural buffers like mangroves and forests, community education and regional cooperation","Natural disasters cannot be prepared for","Only foreign aid can reduce disaster vulnerability","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what legacy Caribbean youth inherit from those who came before them?","options":["A rich diverse culture, hard-won independence, beautiful natural environment and the responsibility to preserve and improve all of these for the next generation","Caribbean youth have no particular legacy to consider","Only history books record what previous generations achieved","None of the above"],"correctIndex":0}
],

20: [
  {"question":"A student is asked to evaluate SVG's development challenges using a graph of GDP, poverty rates and emigration from 1990 to 2020. Which conclusion is BEST supported if GDP grew but poverty and emigration also remained high?","options":["Economic growth did not reach all citizens equally suggesting a need for more inclusive development policies","Growth always eliminates poverty","The data is not useful for analysis","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why the Caribbean region is considered important to global biodiversity conservation?","options":["The Caribbean is a biodiversity hotspot with many endemic species found nowhere else; losing Caribbean ecosystems would be an irreversible loss to global natural heritage","Caribbean biodiversity is no different from anywhere else","Only tropical rainforests matter for global biodiversity","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how a Caribbean student can contribute to sustainable development in their community right now?","options":["By conserving resources, reducing waste, supporting local businesses, participating in clean-up projects and learning about and advocating for environmental protection","Students can only contribute after they finish school","Only adults can contribute to sustainable development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains the relationship between colonialism, migration and Caribbean diaspora communities?","options":["Colonial ties made it easier for Caribbean people to migrate to Britain France and the Netherlands; these diaspora communities now send remittances and maintain cultural and economic links","Caribbean migration had no connection to colonialism","The diaspora has no ongoing connection to Caribbean development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what it means for the Caribbean to pursue energy sovereignty?","options":["Developing domestic renewable energy from solar, wind, geothermal and hydro sources so that Caribbean nations are not dependent on imported fossil fuels subject to global price changes","Buying more fossil fuels from friendly countries","Reducing all energy use to zero","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the tension between national development and environmental protection in the Caribbean?","options":["Economic growth often requires resource extraction and development that can harm the environment; sustainable development seeks approaches that achieve growth while protecting natural assets for the future","There is no tension between development and environment","Development always improves the environment","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why celebrating local Caribbean culture matters for a young Vincentian?","options":["It builds pride in one's identity and heritage, strengthens community bonds and preserves the unique cultural expressions that make SVG and the Caribbean special in the world","Local culture is not worth celebrating","Only international culture has value","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what the evidence suggests about the impact of climate change on Caribbean coral reefs?","options":["Rising ocean temperatures are causing widespread coral bleaching and reef degradation that threatens marine ecosystems, fishing and tourism across the Caribbean","Coral reefs are completely unaffected by climate change","Only pollution not climate change affects reefs","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what responsible citizenship means for a Caribbean student today?","options":["Learning about rights and responsibilities, respecting the environment and others, participating in community life and preparing to contribute to Caribbean development","Citizenship only becomes relevant after age 18","Responsible citizenship only means following rules","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why CARICOM continues to be relevant for Caribbean development in the 21st century?","options":["The Caribbean's small size means collective action on trade, climate advocacy, security and development gives member states far more influence and resilience than they would have acting alone","CARICOM is no longer relevant","CARICOM only benefits the largest Caribbean countries","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes the overall vision for sustainable development in the Caribbean?","options":["Building prosperous societies that protect their natural and cultural heritage, ensure all citizens share in development gains and can withstand the challenges of climate change and globalisation","Only economic growth matters for Caribbean development","The Caribbean cannot achieve sustainable development","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST explains why SVG's cultural diversity is a strength rather than a weakness?","options":["The contributions of Vincentian Africans, Caribs, Garifuna, Indians, Europeans and others have created a rich vibrant society with multiple perspectives, skills and traditions","Diversity causes only conflict","Only a single culture can create a strong society","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes how Caribbean nations can use their shared history to build regional solidarity?","options":["Recognising the common experiences of colonialism, slavery, independence and development challenges creates empathy and mutual support among Caribbean peoples","Caribbean nations have no significant shared history","Regional solidarity has no practical benefits","None of the above"],"correctIndex":0},
  {"question":"A student reads that SVG's main export earners have shifted over 50 years from agriculture to services. What does this BEST reflect about economic development?","options":["Economies evolve over time and Caribbean nations must continuously adapt their skills, education and infrastructure to support changing economic structures","Economies never change their structure","Agricultural decline is always negative","None of the above"],"correctIndex":0},
  {"question":"Which of the following BEST describes what the ideal Caribbean citizen of the future looks like according to CPEA Social Studies values?","options":["An informed, responsible and active person who respects their heritage, protects their environment, participates in democracy and contributes to the sustainable development of their community and region","Only an economically productive person","Only someone who follows all rules without question","None of the above"],"correctIndex":0}
]

}

for level, questions in data.items():
    filepath = os.path.join(OUT, f"cpea_social_studies_l{level}.json")
    with open(filepath, 'w') as f:
        json.dump(questions, f, indent=2)
    print(f"Written level {level}")

print("Levels 11-20 done!")
